JoeFalzonWebSite/backend_flask/my_app/modules/views/_clients.py
from my_app import app
from flask import Blueprint, render_template, redirect, request, url_for, jsonify, session

from my_app.modules.forms import ClientForm

# ______________________________________________________________________


my_clients = Blueprint('my_clients', __name__, url_prefix='/clients')


# ______________________________________________________________________

@my_clients.route('/add', methods=['POST', 'GET'])
def add_client():

    submitted = False
    if request.method == 'POST':
        submitted = True
    form = ClientForm() 
    print(form.validate())
    if form.validate_on_submit():        

        title = form.title.data
        firstname = form.firstname.data
        lastname = form.lastname.data
        id_card = form.id_card.data
        company = form.company.data
        filenumber = form.filenumber.data
        phone = form.phone.data
        mobile = form.mobile.data
        email = form.email.data
        street = form.street.data
        city = form.city.data
        country = form.country.data
        postcode = form.postcode.data

        test = f"""
            {title} <br> {firstname} <br> {lastname} <br> {id_card} <br> 
            {company} <br> {filenumber} <br> {phone} <br> {mobile} <br> 
            {email} <br> {street} <br> {city} <br> {country} <br> {postcode}
            """

        return f"<h4>{test}</h4>"


    return render_template('clients/add-client.html', form=form, submitted=submitted)

# _____________________________

JoeFalzonWebSite/backend_flask/my_app/modules/views/views_clients.py
from my_app import app, db
from flask import Blueprint, render_template, redirect, request, url_for, jsonify, session, flash, Markup

from my_app.modules.forms import ClientForm, DeleteAllForm
from my_app.modules.database import JFW_Clients
from flask_login import login_required

from datetime import datetime, timezone, tzinfo

from sqlalchemy import asc, desc

# ______________________________________________________________________


my_clients = Blueprint('my_clients', __name__, url_prefix='/clients')


# ______________________________________________________________________
# ______________________________________________________________________



@my_clients.route('/all-clients/')
@login_required
def all_clients():

    # ---- sorting table when click row header --------------------
    
    sort_column = 'id'
    sort_dir = 'DESC'

    form = DeleteAllForm()

    if len(request.args) >= 2:
        sort_column = request.args['sort']
        sort_dir = request.args['dirc']
    
    if sort_dir == 'ASC':
        sort = asc(sort_column)
    else:
        sort = desc(sort_column)     


    # ---- geting list of clients from db -------------------------

    clients = JFW_Clients.query.order_by(sort).all()


    # ---- looping clients ----------------------------------------

    # i is use to add 'clients__shade' class on each alternating row
    i = 1 

    for c in clients:
        i = i * -1
        if i < 0:
            c._class = 'clients__row clients__shade'
        else:
            c._class = 'clients__row'

        # update utctime to local timezone and changing date format
        local_time_zone = datetime.now() - datetime.utcnow()
        c.registered = c.registered + local_time_zone
        c.registered = c.registered.strftime('%d-%B-%Y | %X')

    # ------------------------------------------------------------

    return render_template('clients/all-clients.html', clients=clients, edit=None, form=form)


# _____________________________
# _____________________________


@my_clients.route('/add', methods=['POST', 'GET'])
@login_required
def add_client():


    form = ClientForm() 
   
    if form.validate_on_submit():        

        title = form.title.data
        firstname = form.firstname.data
        lastname = form.lastname.data
        id_card = form.id_card.data
        company = form.company.data
        filenumber = form.filenumber.data
        phone = form.phone.data
        mobile = form.mobile.data
        email = form.email.data
        street = form.street.data
        city = form.city.data
        country = form.country.data
        postcode = form.postcode.data

        if not filenumber: filenumber = 0
        if not phone: phone = 0
        if not mobile: mobile = 0
        

        new_client = JFW_Clients(
                        title=title, firstname=firstname, lastname=lastname,
                        id_card=id_card, company=company, filenumber=filenumber,
                        phone=phone, mobile=mobile, email=email, street=street, 
                        city=city, country=country, postcode=postcode
                    )
        db.session.add(new_client)
        db.session.commit()    

        flash(
            'Client has been added successfully!'
            , 'flash flash--success'
        )

        return redirect(url_for('my_clients.all_clients'))


    return render_template('clients/add-client.html', form=form)

# _____________________________
# _____________________________


@my_clients.route('/edit-client/<id>/', methods=['POST', 'GET'])
@login_required
def edit_client(id):

    form = ClientForm() 

    client = JFW_Clients.query.filter_by(id=id).first()
    form.title.data = client.title

    if form.validate_on_submit():

        client.title = form.title.data
        client.firstname = form.firstname.data
        client.lastname = form.lastname.data
        client.id_card = form.id_card.data
        client.company = form.company.data
        client.filenumber = form.filenumber.data
        client.phone = form.phone.data
        client.mobile = form.mobile.data
        client.email = form.email.data
        client.street = form.street.data
        client.city = form.city.data
        client.country = form.country.data
        client.postcode = form.postcode.data

        if not client.filenumber: client.filenumber = 0
        if not client.phone: client.phone = 0
        if not client.mobile: client.mobile = 0

        db.session.commit()

        flash(Markup(
            'Client has been successfully updated! &nbsp;<a href="../../all-clients">View all Clients</a>')
            , 'flash flash--success'
        )


    return render_template('clients/edit-client.html', form=form, edit=client)

# _____________________________
# _____________________________

@my_clients.route('/delete-client/<id>/', methods=['GET'])
@login_required
def delete_client(id):

    client = JFW_Clients.query.get(id)
    if client:
        db.session.delete(client)
        db.session.commit()

        flash(
            'Client has been removed successfully!'
            , 'flash flash--warning'
        )

    return redirect(url_for('my_clients.all_clients'))

# _____________________________
# _____________________________

@my_clients.route('/delete-clients', methods=['POST'])
@login_required
def delete_clients():

    # ___________________
    
    # get list of checked clients
    clients_list = request.form.getlist("checkBoxList")
    # change each client id from str to int
    clients_list = map(int, clients_list)
    # change list to tuple
    clients_list = tuple(clients_list)

    print(clients_list)

    # ___________________

    
    

    if len(clients_list) < 1:
        message = 'No Clients has been selected!'
    else:      

        delete_count = clients_list = JFW_Clients.query.filter(
            JFW_Clients.id.in_(clients_list)
        ).delete(synchronize_session=False)

        db.session.commit()

        print(repr(delete_count))

        if delete_count == 1 :
            c = 'client '
        else: 
            c = 'clients'

        message = f'{delete_count} {c} has been removed successfully!'

 
        

    # ___________________
 
    flash(Markup(message), 'flash flash--warning')

    return redirect(url_for('my_clients.all_clients'))

JoeFalzonWebSite/backend_flask/my_app/templates/clients/add-client.html
{% extends 'main.html' %}
{% from "macro.html" import render_field %}

{% block title %}{% endblock %}

{% block main %}                
<div class="addin">           
    <form   action="{{url_for('my_clients.add_client')}}" method="POST" 
            class="myform addin__layout addin__form" 
            enctype="multipart/form-data" novalidate role="form">

        <h2 class="myform__title addin__title">add client</h2>

        {{ form.csrf_token }}
       
        {{ render_field(form.title, 'title') }}
        
        {{ render_field(form.firstname, 'firstname') }}                            
        
        {{ render_field(form.lastname, 'lastname') }}                            
        
        {{ render_field(form.id_card, 'id_card') }}                            
        
        {{ render_field(form.company, 'company') }}                            
        
        {{ render_field(form.filenumber, 'filenumber') }}                            
        
        {{ render_field(form.phone, 'phone') }}                            
        
        {{ render_field(form.mobile, 'mobile') }}                            
        
        {{ render_field(form.email, 'email') }}                            
        
        {{ render_field(form.street, 'street') }}                            
        
        {{ render_field(form.city, 'city') }}                            
        
        {{ render_field(form.country, 'country') }}                            
        
        {{ render_field(form.postcode, 'postcode') }}  
        
        {{ form.submit(class="btn btn--dark myform__btn addin__btn mt-lg", value="add client") }}
        
        

    </form>
</div>
{% endblock %}

JoeFalzonWebSite/backend_flask/my_app/templates/clients/all-clients.html
{% extends 'main.html' %}


{% block title %}{% endblock %}

{% block main %}  


<form action="{{url_for('my_clients.delete_clients')}}" method="POST">
    {{ form.csrf_token }}
<div class="form-nav">
    <ul class="form-nav__list">
        <li class="form-nav__item">List {{clients|count}}</li>
        <li class="form-nav__item form-nav__item--create"><a href="{{url_for('my_clients.add_client')}}">Create</a></li>
        <li class="form-nav__item form-nav__item--export"><a href="#">Export</a></li>
        <li class="form-nav__item form-nav__item--delete delete-btn"><button type="submit">Delete</button></li>
    </ul>
</div>

{% include 'flash-message.html' %}
                
<div class="clients">
    <div class="clients__row">
        <div class="clients__item clients__item--header clients__item--header--checkbox">
            <input type="checkbox" id="client-checkbox-all">
        </div>
        
        <div class="clients__item"></div>

        <div class="clients__item clients__item--header clients__item--header--id"
        ><a href="?sort=id&dirc=ASC">id</a><i class="fas"></i></div>

        <div class="clients__item clients__item--header clients__item--header--firstname"
        ><a href="?sort=firstname&dirc=ASC">name</a><i class="fas"></i></div>

        <div class="clients__item clients__item--header clients__item--header--lastname"
        ><a href="?sort=lastname&dirc=ASC">surname</a><i class="fas"></i></div>

        <div class="clients__item clients__item--header clients__item--header--id_card"
        ><a href="?sort=id_card&dirc=ASC">ID number</a><i class="fas"></i></div>

        <div class="clients__item clients__item--header clients__item--header--company"
        ><a href="?sort=company&dirc=ASC">company</a><i class="fas"></i></div>

        <div class="clients__item clients__item--header clients__item--header--filenumber"
        ><a href="?sort=filenumber&dirc=ASC">filenumber</a><i class="fas"></i></div>

        <div class="clients__item clients__item--header clients__item--header--contact"
        >contact</div>

        <div class="clients__item clients__item--header clients__item--header--email"
        ><a href="?sort=email&dirc=ASC">email</a><i class="fas"></i></div>

        <div class="clients__item clients__item--header clients__item--header--city"
        ><a href="?sort=city&dirc=ASC">city</a><i class="fas"></i></div>

        <div class="clients__item clients__item--header clients__item--header--street"
        ><a href="?sort=street&dirc=ASC">street</a><i class="fas"></i></div>

        <div class="clients__item clients__item--header clients__item--header--registerd"
        ><a href="?sort=id&dirc=ASC">registerd</a><i class="fas"></i></div>

    </div>

    {% for c in clients %}
    <div class="{{c._class}}">
        <div class="clients__item clients__item--checkbox" >
            <input class="client-checkbox" type="checkbox"  name="checkBoxList" value="{{c.id}}">
        </div>

        <div class="clients__item clients__item--delete">
            <a href="{{url_for('my_clients.edit_client', id=c.id)}}"><i class="fas fa-pencil-alt"></i></a>
            <a href="{{url_for('my_clients.delete_client', id=c.id)}}"><i class="fas fa-trash delete-btn"></i></a>
            <a href="#"><i class="fas fa-eye"></i></a>
        </div>

        <div class="clients__item clients__item--id">{{c.id}}</div>
        <div class="clients__item clients__item--firstname">{{c.firstname}}</div>
        <div class="clients__item clients__item--lastname">{{c.lastname}}</div>
        <div class="clients__item clients__item--id_card">{{c.id_card}}</div>
        <div class="clients__item clients__item--company">{{c.company}}</div>
        <div class="clients__item clients__item--filenumber">{{c.filenumber}}</div>
        <div class="clients__item clients__item--contact">{{c.phone}}/{{c.mobile}}</div>
        <div class="clients__item clients__item--email">{{c.email}}</div>
        <div class="clients__item clients__item--city">{{c.city}}</div>
        <div class="clients__item clients__item--street">{{c.street}}</div>
        <div class="clients__item clients__item--registerd">{{c.registered}}</div>
    </div>
    {% endfor %}  
    
   
    
</div>
</form>

{% endblock %}

JoeFalzonWebSite/backend_flask/my_app/templates/clients/edit-client.html
{% extends 'main.html' %}
{% from "macro.html" import render_field %}

{% block title %}{% endblock %}

{% block main %}                
<div class="addin">           
    <form   action="{{url_for('my_clients.edit_client', id=edit.id)}}" method="POST" 
            class="myform addin__layout addin__form" 
            enctype="multipart/form-data" novalidate role="form">
            
        <h2 class="myform__title addin__title">update client info</h2>


        {% include 'flash-message.html' %}
        
        {{ form.csrf_token }}        
        
        {{ render_field(form.title, 'title', edit.title) }}    

        {{ render_field(form.firstname, 'firstname', edit.firstname) }}                            
        
        {{ render_field(form.lastname, 'lastname', edit.lastname) }}                            
        
        {{ render_field(form.id_card, 'id_card', edit.id_card) }}                            
        
        {{ render_field(form.company, 'company', edit.company) }}                            
        
        {{ render_field(form.filenumber, 'filenumber', edit.filenumber) }}                            
        
        {{ render_field(form.phone, 'phone', edit.phone) }}                            
        
        {{ render_field(form.mobile, 'mobile', edit.mobile) }}                            
        
        {{ render_field(form.email, 'email', edit.email) }}                            
        
        {{ render_field(form.street, 'street', edit.street) }}                            
        
        {{ render_field(form.city, 'city', edit.city) }}                            
        
        {{ render_field(form.country, 'country', edit.country) }}                            
        
        {{ render_field(form.postcode, 'postcode', edit.postcode) }}  
        
        {{ form.submit(class="btn btn--dark myform__btn addin__btn mt-lg", value="update client") }}        
        

    </form>
</div>
{% endblock %}