JoeFalzonWebSite/backend_flask/my_app/modules/views/_clients.py
from my_app import app
from flask import Blueprint, render_template, redirect, request, url_for, jsonify, session

from my_app.modules.forms import ClientForm

# ______________________________________________________________________


my_clients = Blueprint('my_clients', __name__, url_prefix='/clients')


# ______________________________________________________________________

@my_clients.route('/add', methods=['POST', 'GET'])
def add_client():

    submitted = False
    if request.method == 'POST':
        submitted = True
    form = ClientForm() 
    print(form.validate())
    if form.validate_on_submit():        

        title = form.title.data
        firstname = form.firstname.data
        lastname = form.lastname.data
        id_card = form.id_card.data
        company = form.company.data
        filenumber = form.filenumber.data
        phone = form.phone.data
        mobile = form.mobile.data
        email = form.email.data
        street = form.street.data
        city = form.city.data
        country = form.country.data
        postcode = form.postcode.data

        test = f"""
            {title} <br> {firstname} <br> {lastname} <br> {id_card} <br> 
            {company} <br> {filenumber} <br> {phone} <br> {mobile} <br> 
            {email} <br> {street} <br> {city} <br> {country} <br> {postcode}
            """

        return f"<h4>{test}</h4>"


    return render_template('clients/add-client.html', form=form, submitted=submitted)

# _____________________________

JoeFalzonWebSite/backend_flask/my_app/modules/views/_projects.py
from my_app import app
from flask import Blueprint, render_template, redirect, request, url_for, jsonify, session



# ______________________________________________________________________


my_projects = Blueprint('my_projects', __name__, url_prefix='/projects')

# ______________________________________________________________________


@my_projects.route('/')
def dashbord():

    return render_template('main.html')

# _____________________________



@my_projects.route('/all-projects')
def all_projects():

    return render_template('projects/all-projects.html')

# _____________________________

@my_projects.route('/add/')
def add_project():

    return render_template('projects/add-project.html')

# _____________________________

JoeFalzonWebSite/backend_flask/my_app/modules/views/views_admin.py
from my_app import app, lodin_manager
from flask import Blueprint, render_template, redirect, request, \
                  url_for, jsonify, session, flash, session

from flask_login import login_user, login_required, logout_user
from my_app.modules.forms import SignInForm
from my_app.modules.database import JFW_Users

from my_app.modules.database import db

# ______________________________________________________________________

@lodin_manager.user_loader
def load_user(session_token):
    return JFW_Users.query.filter_by(session_token=session_token).first()
# ______________________________________________________________________


my_admin = Blueprint('my_admin', __name__, url_prefix='/')

# ______________________________________________________________________

@my_admin.route('/')
@login_required
def index():

    return render_template('main.html')

# _____________________________


@my_admin.route('/sign-in', methods=['POST', 'GET'])
def sign_in():

    form = SignInForm()


    if form.validate_on_submit():

        email = form.email.data 
        password = form.password.data
        remember = form.remember.data 


        signin_user = JFW_Users.query.filter_by(email=email).first()        
            

        if not signin_user:
            flash('The email you entered isn’t connected to an account.')
        
        elif not signin_user.check_password(signin_user.password, password):
            flash('The password you’ve entered is incorrect.')
        else:            
            signin_user.user_sign_in()
            signin_user.update_session_token()
            db.session.commit()
 
            login_user(signin_user, remember=remember)
            
            if 'next' in session:
                return redirect(session['next'])
            else:
                return redirect(url_for('my_projects.all_projects'))
                   

        

    return render_template('sign-in.html', form=form)


# _____________________________


@my_admin.route('/sign-out/')
def sign_out():
    logout_user()
    return redirect(url_for('my_admin.sign_in'))


# _____________________________


@my_admin.route('/test/')
@login_required
def test():
    return 'Test Ok!'

JoeFalzonWebSite/backend_flask/my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Styles     -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/css/style.css') }}">
    <!-- Font Awesome   -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- Ckeditor5      -->
    <script src="https://cdn.ckeditor.com/ckeditor5/25.0.0/classic/ckeditor.js"></script>

    <title>myAdmin{% block title %}base{% endblock %}</title>
</head>
<body>

    {% block body %}base{% endblock %}

    <script src="{{ url_for('static', filename='script/script.js') }}"></script>

</body>
</html>

JoeFalzonWebSite/backend_flask/my_app/templates/error.html
{% extends 'base.html' %}

{% block body %}
<div class="error">
	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404"></div>
			<h1>{{code}}</h1>
			<h2>{{name}}</h2>
			<p>{{description}}</p>
			<a href="{{url_for('my_projects.all_projects')}}">Back to homepage</a>
		</div>
	</div>
</div>   

{% endblock %}

JoeFalzonWebSite/backend_flask/my_app/templates/flash-message.html
<div class="flash__container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <p class="mb-sm ta-c {{ category }}">{{ message }}</p>
        {% endfor %}
    {% endif %}
    {% endwith %}
</div> 

JoeFalzonWebSite/backend_flask/my_app/templates/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="../static/styles/css/style.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <title>Login Page</title>
</head>
<body>

    <div class="login">
        <div class="login__layout">

            

            <form action="#" method="POST" class="myform login__form">

                <h2 class="myform__title">Welcome to myAdmin</h2>

                <div class="myform__group myform__group--1">
                    <label for="email" class="myform__label">email</label>
                    <input type="text" name="email" class="myform__input">                    
                </div>

                <div class="myform__group myform__group--2">
                    <label for="password" class="myform__label">password</label>
                    <a href="#" class="myform__link">Forgot your password?</a>
                    <input type="password" name="password" class="myform__input" id="password-field">  

                    <span toggle="#password-field"  id="toggle-password"
                    class="fa fa-fw fa-eye-slash myform__icon--toggle-password"></span>
                </div>



                <label class="checkbox mb-lg">Remember this device
                    <input type="checkbox" checked="checked">
                    <span class="checkmark"></span>
                </label>

                <button class="btn btn--dark myform__btn">sign in</button>

            </form>

        </div>
    </div>

    <footer class="footer">
        <script src="../static/script/script.js"></script>
    </footer>
</body>
</html>

JoeFalzonWebSite/backend_flask/my_app/templates/macro.html
<!-- --------------------------------------------------------------- -->

{% macro render_field(field, fieldname, edit) %}

{% set inputclasses = "myform__input " + "myform__input--" ~ fieldname %}
{% set groupclasses = "myform__group " + "addin__group--"  ~ fieldname %}


<div class="{{groupclasses}}">
    {{ field.label( class="myform__label", for=fieldname)  }} 

    {% if fieldname in ['name', 'address', 'locality', 'firstname', 'lastname', 'id_card', 'street', 'city', 'country'] %}
    <span style="color: crimson;">&nbsp;*<span>
    {% endif %}
    
    {% if field.errors %} 
        <span class="myform__error">{% for error in field.errors %} {{error}} {% endfor %}</span>
    {% endif %}

    {{ field( class=inputclasses, value=edit)}} 
</div>

{% endmacro %}

<!-- --------------------------------------------------------------- -->

{% macro render_error_message(field) %}

    {% if field.errors %}
    <span class="myform__error">{% for error in field.errors %} {{error}} {% endfor %}</span>
    {% endif %}

{% endmacro %}

<!-- --------------------------------------------------------------- -->

JoeFalzonWebSite/backend_flask/my_app/templates/main.html
{% extends 'base.html' %}

{% block title %}
    body layout
{% endblock %}

{% block body %}

<div class="body__layout">

<!-- --------------------------------------------------------------- -->

<nav class="nav">
    <div class="nav__layout">

        <a href="{{url_for('my_projects.all_projects')}}" class="nav__logo"><img src="{{url_for('static', filename='images/my_admin_white.png')}}" alt=""> myAdmin</a>

        <div class="nav__main">
            <a href="" class="nav__link"><i class="fas fa-comment"></i></a>
            <a href="" class="nav__link"><i class="far fa-bell"></i></a>
        </div>

        <input type="checkbox" checked class="dropdown--user--toggle" id="user-dropdown">
        <div class="dropdown dropdown--user">
            <ul class="dropdown__list">
                <li class="dropdown__item"><i class="fas fa-cog"></i></i><a href="#">Settings</a></li>
                <li class="dropdown__item"><i class="far fa-user"></i><a href="#">Profile</a></li>
                <li class="dropdown__item"><i class="fas fa-power-off"></i><a href="{{url_for('my_admin.sign_out')}}">Logout</a></li>
                <li class="dropdown__item"><i class="fas fa-power-off"></i><a href="{{url_for('my_admin.sign_in')}}">Sign-in</a></li>
            </ul>
        </div> 

        <div class="nav__user">
            <i class="fas fa-user"></i>
            <p>Joseph Falzon</p>
            <i class="fas fa-sort-down mt-tn-n"></i>                    
        </div>

    </div>
</nav>

<!-- --------------------------------------------------------------- -->

<aside class="sidebar" id="sidebar">
    <div class="sidebar__layout" id="sidebar">
        
        <button class="sidebar__btn" ><i id="sidebar__btn" class="fas fa-angle-double-right"></i></button>
        <ul class="sidebar__menu sidebar__off" id="sidebar__menu">
            <li class="sidebar__item"><a href="#"><i class="fas fa-home"></i>Dashbord</a></li>
            <li class="sidebar__item"><a href="{{ url_for('my_clients.all_clients') }}"><i class="fas fa-user-friends"></i>Clients</a></li>
            <li class="sidebar__item"><a href="{{ url_for('my_clients.add_client') }}"><i class="fas fa-plus"></i>Add New Client</a></li>
            <li class="sidebar__item"><a href="{{ url_for('my_projects.all_projects') }}"><i class="fas fa-border-all"></i>Projects</a></li>
            <li class="sidebar__item"><a href="{{ url_for('my_projects.add_project') }}"><i class="fas fa-plus"></i>Add New Project</a></li>
            <li class="sidebar__item"><a href="#"><i class="fas fa-puzzle-piece"></i>Categories</a></li>
            <li class="sidebar__item"><a href="#"><i class="fas fa-wave-square"></i>Status</a></li>
            <li class="sidebar__item"><a href="#"><i class="far fa-calendar-check"></i>Year</a></li>
        </ul>
        
    </div>
</aside>

<!-- --------------------------------------------------------------- -->

<main class="main" id="main">
    <div class="main__layouts">
        
        {% block main %}{% endblock %}    

    </div>
</main>

</div>

<!-- --------------------------------------------------------------- -->

{% endblock %}

JoeFalzonWebSite/backend_flask/my_app/templates/sign-in.html
{% extends 'base.html' %}

{% from "macro.html" import render_error_message %}

{% block title %}{% endblock %}

{% block body %}

<div class="login">
    <div class="login__layout">
        

        <form action="{{ url_for('my_admin.sign_in') }}" method="POST" class="myform login__form" role="form" novalidate>

            <h2 class="myform__title">Welcome to myAdmin</h2>
            {{ form.csrf_token }}
            <div class="myform__group myform__group--1">
                {{ form.email.label(class="myform__label") }}  
                {{ render_error_message(form.email) }}
                {{ form.email(class="myform__input") }}                  
            </div>

            <div class="myform__group myform__group--2">
                {{ form.password.label(class="myform__label") }}

                <a href="#" class="myform__link">Forgot your password?</a>

                

                {{ form.password(class="myform__input", id="password-field", type="password") }} 
                {{ render_error_message(form.password) }}

                <span toggle="#password-field"  id="toggle-password"
                class="fa fa-fw fa-eye-slash myform__icon--toggle-password"></span>
            </div>

            <label class="checkbox mb-lg">        
                {{ form.remember.label() }}                
                {{ form.remember(checked="checked") }}
                <span class="checkmark"></span>
            </label>

            {{ form.submit(class="btn btn--dark myform__btn", value="sign in") }}

            <!-- --------------------------------------------------- -->

                {% with messages = get_flashed_messages() %}
                {% if messages %}
        
                    <ul class="myform__flash">
                    {% for message in messages %}
                        <li class="mt-sm">{{ message }}</li>
                    {% endfor %}
                    </ul>
        
                {% endif %}
            {% endwith %}

            <!-- --------------------------------------------------- -->

        </form>

    </div>
</div>

{% endblock %}